"""Add project Table

Revision ID: 2b7a5c36d4de
Revises: 457b3512e751
Create Date: 2026-03-28 01:52:10.907240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7a5c36d4de'
down_revision: Union[str, None] = '457b3512e751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.add_column('task', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_constraint('task_lead_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('task_attachment', 'mime_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint('task_attachment_task_id_fkey', 'task_attachment', type_='foreignkey')
    op.create_foreign_key(None, 'task_attachment', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_comment_task_id_fkey', 'task_comment', type_='foreignkey')
    op.create_foreign_key(None, 'task_comment', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_comment', type_='foreignkey')
    op.create_foreign_key('task_comment_task_id_fkey', 'task_comment', 'task', ['task_id'], ['id'])
    op.drop_constraint(None, 'task_attachment', type_='foreignkey')
    op.create_foreign_key('task_attachment_task_id_fkey', 'task_attachment', 'task', ['task_id'], ['id'])
    op.alter_column('task_attachment', 'mime_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_lead_id_fkey', 'task', 'user', ['lead_id'], ['id'])
    op.drop_column('task', 'project_id')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
