"""Added profile fields and social links

Revision ID: 4bbede36a673
Revises: c4c4d9c66836
Create Date: 2026-01-03 01:37:23.424185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbede36a673'
down_revision: Union[str, None] = 'c4c4d9c66836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('x_link', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('of_link', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('insta_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'insta_link')
    op.drop_column('user', 'of_link')
    op.drop_column('user', 'x_link')
    # ### end Alembic commands ###
