"""Add table for finance Management

Revision ID: 6bed6ed75b1b
Revises: a3a0c32879c6
Create Date: 2026-04-03 19:51:16.883579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bed6ed75b1b'
down_revision: Union[str, None] = 'a3a0c32879c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_head',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_head_id'), 'expense_head', ['id'], unique=False)
    op.create_index(op.f('ix_expense_head_name'), 'expense_head', ['name'], unique=True)
    op.create_table('financial_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_type', sa.Enum('cash_in', 'cash_out', name='transaction_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'bank_transfer', 'cheque', 'mobile_wallet', 'other', name='payment_method_enum'), nullable=False),
    sa.Column('expense_head_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['expense_head_id'], ['expense_head.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transaction_id'), 'financial_transaction', ['id'], unique=False)
    op.create_index(op.f('ix_financial_transaction_transaction_date'), 'financial_transaction', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_financial_transaction_transaction_type'), 'financial_transaction', ['transaction_type'], unique=False)
    op.create_table('salary_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allowance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('salary_month', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'paid', name='salary_status_enum'), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transaction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_record_id'), 'salary_record', ['id'], unique=False)
    op.create_index(op.f('ix_salary_record_salary_month'), 'salary_record', ['salary_month'], unique=False)
    op.create_index(op.f('ix_salary_record_user_id'), 'salary_record', ['user_id'], unique=False)
    op.drop_index('ix_model_invoice_id', table_name='model_invoice')
    op.drop_index('ix_model_invoice_invoice_date', table_name='model_invoice')
    op.drop_table('model_invoice')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_invoice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('subscription', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tips', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('posts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('messages', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('referrals', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('streams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('others', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='model_invoice_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='model_invoice_pkey')
    )
    op.create_index('ix_model_invoice_invoice_date', 'model_invoice', ['invoice_date'], unique=False)
    op.create_index('ix_model_invoice_id', 'model_invoice', ['id'], unique=False)
    op.drop_index(op.f('ix_salary_record_user_id'), table_name='salary_record')
    op.drop_index(op.f('ix_salary_record_salary_month'), table_name='salary_record')
    op.drop_index(op.f('ix_salary_record_id'), table_name='salary_record')
    op.drop_table('salary_record')
    op.drop_index(op.f('ix_financial_transaction_transaction_type'), table_name='financial_transaction')
    op.drop_index(op.f('ix_financial_transaction_transaction_date'), table_name='financial_transaction')
    op.drop_index(op.f('ix_financial_transaction_id'), table_name='financial_transaction')
    op.drop_table('financial_transaction')
    op.drop_index(op.f('ix_expense_head_name'), table_name='expense_head')
    op.drop_index(op.f('ix_expense_head_id'), table_name='expense_head')
    op.drop_table('expense_head')
    # ### end Alembic commands ###
