"""Update Notification table add Emums

Revision ID: 7cf2b6835475
Revises: 2c46aa58d3ed
Create Date: 2026-01-31 01:56:41.385566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf2b6835475'
down_revision: Union[str, None] = '2c46aa58d3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('notification', sa.Column('severity', sa.String(length=20), nullable=True))
    op.create_index('ix_notif_recipient_read_created', 'notification', ['recipient_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_category'), 'notification', ['category'], unique=False)
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_index(op.f('ix_notification_category'), table_name='notification')
    op.drop_index('ix_notif_recipient_read_created', table_name='notification')
    op.drop_column('notification', 'severity')
    op.drop_column('notification', 'category')
    # ### end Alembic commands ###
