"""Add User Assignment

Revision ID: ab9cf016376d
Revises: 4bbede36a673
Create Date: 2026-01-06 17:42:45.953136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9cf016376d'
down_revision: Union[str, None] = '4bbede36a673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('assigned_model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['assigned_model_id'], ['id'])
    op.create_foreign_key(None, 'user', 'user', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'assigned_model_id')
    op.drop_column('user', 'manager_id')
    # ### end Alembic commands ###
