"""update in Task Model

Revision ID: abd4f362a7e4
Revises: 41b0a9b7a3f4
Create Date: 2026-01-09 18:29:56.885470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd4f362a7e4'
down_revision: Union[str, None] = '41b0a9b7a3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
