"""Adding New Table For Invoice

Revision ID: c8e254bb4c84
Revises: fc54dd0beab8
Create Date: 2026-01-22 21:28:25.768348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e254bb4c84'
down_revision: Union[str, None] = 'fc54dd0beab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('subscription', sa.Float(), nullable=True),
    sa.Column('tips', sa.Float(), nullable=True),
    sa.Column('posts', sa.Float(), nullable=True),
    sa.Column('messages', sa.Float(), nullable=True),
    sa.Column('referrals', sa.Float(), nullable=True),
    sa.Column('streams', sa.Float(), nullable=True),
    sa.Column('others', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_invoice_id'), 'model_invoice', ['id'], unique=False)
    op.create_index(op.f('ix_model_invoice_invoice_date'), 'model_invoice', ['invoice_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_invoice_invoice_date'), table_name='model_invoice')
    op.drop_index(op.f('ix_model_invoice_id'), table_name='model_invoice')
    op.drop_table('model_invoice')
    # ### end Alembic commands ###
